// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYuZ3q5TnMbkO5okCnjxG3jzQr5NomaaY',
    appId: '1:933202759364:web:353a8c91a509f2549ec391',
    messagingSenderId: '933202759364',
    projectId: 'vhgp-9b167',
    authDomain: 'vhgp-9b167.firebaseapp.com',
    storageBucket: 'vhgp-9b167.appspot.com',
    measurementId: 'G-84FKEQYVZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCerZsxXfs8Ol5jPn5AAY9Mu58SIxMlF-I',
    appId: '1:933202759364:android:fd364c01132dab1e9ec391',
    messagingSenderId: '933202759364',
    projectId: 'vhgp-9b167',
    storageBucket: 'vhgp-9b167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3W71aDklju4ny4NXB1DfTyY10dTXv6Dw',
    appId: '1:933202759364:ios:6830df2f6c690ad19ec391',
    messagingSenderId: '933202759364',
    projectId: 'vhgp-9b167',
    storageBucket: 'vhgp-9b167.appspot.com',
    androidClientId: '933202759364-6k5bfplejn6jlqfou8101atopba57lgt.apps.googleusercontent.com',
    iosClientId: '933202759364-5ae4di3bp9drpeivscph8lib6nfhk9gj.apps.googleusercontent.com',
    iosBundleId: 'com.reso.vhgp.deli.vhgpDeli',
  );
}
